# Generated by Django 5.0.4 on 2024-04-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='backend.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_capitaine',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='backend.team'),
        ),
    ]
