# Generated by Django 5.0.4 on 2024-04-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_match_tournament_match_winner_player_is_capitaine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tournament'),
        ),
    ]
